migrating code from js to ts
ftonato/registrobr pull request #9
Opened 2018-10-03 17:46 UTC by rameshvishnoi90904

2018-10-04 11:40 UTC, ftonato commented
This _pull request_ is not concluded, right?

2018-10-04 11:53 UTC, rameshvishnoi90904 commented
@ftonato This is concluded/

2018-10-04 12:38 UTC, ftonato commented
I'm seeing your' update and a have some questions about this PR:

- Why you changed the variables that has used `const` and `let` to `var`?

2018-10-04 12:42 UTC, ftonato commented
I'm seeing your' update and a have some questions about this PR:

- Why did you change the variables that has used `const` and `let` to `var`?
- Why don't you followed the indentation from our original code?
- Why did you change the strings accents to Unicode?

2018-10-15 12:53 UTC, ftonato requested changes

2018-10-15 12:53 UTC, ftonato commented on cli.js
> +var escape = require('entities');
Why did you change the variables that has used `const` and `let` to `var`?

2018-10-15 12:53 UTC, ftonato commented on cli.js
> +    if (data.available) {
Why don't you followed the indentation from our original code?

2018-10-15 12:53 UTC, ftonato commented on cli.js
> +        console.log(chalk.red("Dom\u00EDnio " + chalk.bold(data.fqdn) + " n\u00E3o est\u00E1 dispon\u00EDvel"));
Why did you change the strings accents to Unicode?

2018-10-15 12:59 UTC, closed without merging